version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    environment:
      - USER_HOST=user-service
      - COMMAND_HOST=commands-service
    ports:
      - "5000:5000"
    depends_on:
      - user-service
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-user:5432/userdb
    expose:
      - "5001"
    depends_on:
      - postgres-user
    networks:
      - backend

  commands-service:
    build:
      context: ./commands-service
      dockerfile: Dockerfile
    container_name: commands_service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-commands:5432/commandsdb
    expose:
      - "5002"
    depends_on:
      - postgres-commands
    networks:
      - backend

  postgres-user:
    image: postgres:16
    container_name: postgres_user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5433:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - db-user

  postgres-commands:
    image: postgres:16
    container_name: postgres_commands
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commandsdb
    ports:
      - "5434:5432"
    volumes:
      - commands-db-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - db-commands

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres-user
      - postgres-commands
    networks:
      - backend

  front:
    build:
      context: ./front-app
      dockerfile: Dockerfile
    container_name: front_app
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://api-gateway:5000
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - backend

networks:
  backend:

volumes:
  user-db-data:
  commands-db-data:
