name: CI - Test API & Databases

on:
  push:
  pull_request:

jobs:
  test_services:
    runs-on: ubuntu-latest

    services:
      postgres-user:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: userdb
        options: >-
          --health-cmd="pg_isready -U postgres -d userdb -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      postgres-commands:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: commandsdb
        options: >-
          --health-cmd="pg_isready -U postgres -d commandsdb -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies (ROOT)
        run: npm install || true


      - name: Install & Build User Service
        working-directory: ./user-service
        run: |
          npm install
          npm run build

      - name: Migrate User DB
        run: |
          psql postgresql://postgres:password@postgres-user:5432/userdb \
            -f user-service/migrations/create_users_table.sql

      - name: Test User DB Connection
        working-directory: ./user-service
        env:
          DATABASE_URL: postgres://postgres:password@postgres-user:5432/userdb
        run: node dist/healthcheck.js

      - name: Install & Build Commands Service
        working-directory: ./commands-service
        run: |
          npm install
          npm run build

      - name: Migrate Commands DB
        run: |
          psql postgresql://postgres:password@postgres-commands:5432/commandsdb \
            -f commands-service/migrations/create_commands_table.sql

      - name: Test Commands DB Connection
        working-directory: ./commands-service
        env:
          DATABASE_URL: postgres://postgres:password@postgres-commands:5432/commandsdb
        run: node dist/healthcheck.js

      - name: Install & Build API Gateway
        working-directory: ./api-gateway
        run: |
          npm install
          npm run build

      - name: Start API Gateway
        working-directory: ./api-gateway
        env:
          USER_HOST: postgres-user
          COMMAND_HOST: postgres-commands
        run: node dist/server.js &

      - name: Wait for API Gateway
        run: |
          for i in {1..20}; do
            curl http://localhost:5000/health && exit 0
            sleep 2
          done
          exit 1
